name: Mirror to GitLab and Codeberg
on:
  push:
    branches: ["**"]
    tags: ["**"]
  delete: {}

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Mirror to GitLab
        run: |
          git push --prune \
            "https://oauth2:${{ secrets.GITLAB_TOKEN }}@gitlab.com/raphazilla/${{ github.event.repository.name }}.git" \
            "refs/heads/*:refs/heads/*" "refs/tags/*:refs/tags/*"
      - name: Mirror to Codeberg
        run: |
          git push --prune \
            "https://raphazilla:${{ secrets.CODEBERG_TOKEN }}@codeberg.org/raphazilla/${{ github.event.repository.name }}.git" \
            "refs/heads/*:refs/heads/*" "refs/tags/*:refs/tags/*"
